apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://apache.github.io/superset
    chart: superset
    targetRevision: "*"
    helm:
      values: |
        supersetNode:
          replicaCount: 1

        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 20Gi

        redis:
          enabled: true
          image:
            registry: docker.io
            repository: redis
            tag: 7.2.4-alpine
          master:
            persistence:
              enabled: true
              storageClass: longhorn
              size: 5Gi

        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: bi
  syncPolicy:
    automated: null
